[workspace]
resolver = "2"
members = [ "calculate-reward", "data_provenance",
  "defi_transaction",
  "energy_usage", "energy_usage_32",
  "financial_protocol",
  "game_logic", "regulatory_compliance", "smart_contract_audit",
  "toy_rsa",
]

[workspace.dependencies]
num-bigint = "0.4"
num-traits = "0.2"
